# Generated by Django 2.0.5 on 2020-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200211_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='levi.png', upload_to='ig/'),
        ),
    ]
