# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20200212_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='ig/'),
        ),
    ]
